#!/bin/bash

pattern(){
number=1
echo -n "Enter number of rows "
read rows
for((i=1; i<=rows; i++))
do
  for((j=1; j<=i; j++))
  do
    echo -n "$number "
    number=$((number + 1))
  done
  number=1
  echo
done
}
pattern
